// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBagEX5SHCgTuN2JjCFsMDces31MfmBWnY',
    appId: '1:382301756016:web:744c7938ba1b110bd072b5',
    messagingSenderId: '382301756016',
    projectId: 'puresty-a823e',
    authDomain: 'puresty-a823e.firebaseapp.com',
    storageBucket: 'puresty-a823e.appspot.com',
    measurementId: 'G-HTBJR1350K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXl5EdTBxJFfCevEleb23Ia0-Kyupx9fI',
    appId: '1:382301756016:android:648fd000c8bdcc09d072b5',
    messagingSenderId: '382301756016',
    projectId: 'puresty-a823e',
    storageBucket: 'puresty-a823e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmnOXxyiRl2xek3ICNkNr5bVHvqnF7JDc',
    appId: '1:382301756016:ios:5d8b0fa1eef68569d072b5',
    messagingSenderId: '382301756016',
    projectId: 'puresty-a823e',
    storageBucket: 'puresty-a823e.appspot.com',
    androidClientId: '382301756016-44h56kjkltoen5jsf5qpjo7pvk50ndtp.apps.googleusercontent.com',
    iosClientId: '382301756016-f14o948asm9iqtdl35lo3cohtmhfvf74.apps.googleusercontent.com',
    iosBundleId: 'com.example.puresty',
  );
}
